/* Folklore field-guide design: editorial warmth, forest-ink depth, and restrained, tactile interaction. */
/* Folklore field-guide design: editorial warmth, forest-ink depth, and restrained, tactile interaction. */
import { type FormEvent, useEffect, useMemo, useState } from "react";
import { Activity, AlertTriangle, ArrowDownRight, ArrowRight, ArrowUpRight, BarChart3, BookOpen, Box, Check, ChevronDown, CircleDollarSign, ClipboardCheck, ClipboardList, Copy, FileText, Flag, Heart, ListFilter, MapPin, Megaphone, Menu, MessageSquareText, Monitor, Moon, PackageSearch, Quote, RotateCcw, ShieldAlert, ShieldCheck, Sparkles, Star, Sun, Target, ThumbsUp, Truck, X } from "lucide-react";

type Agent = { title: string; description: string; note: string; category: string; initials: string; color: string };

const categories = [
  { number: "I.", title: "Customer support", text: "Ticket triage, return handling, FAQ response.", icon: "↗" },
  { number: "II.", title: "Inventory & restocking", text: "Stock alerts, reorder logic, supplier follow-up.", icon: "⌁" },
  { number: "III.", title: "Order fulfillment", text: "Shipping updates, exception handling, tracking.", icon: "□" },
  { number: "IV.", title: "Marketing & ads", text: "Campaign copy, audience notes, performance recaps.", icon: "✳" },
  { number: "V.", title: "Reviews & feedback", text: "Sentiment sorting, response drafts, escalation flags.", icon: "◇" },
];

const agents: Record<string, Agent> = {
  support: { title: "Return & Refund Ticket Drafter", description: "Drafts on-brand replies to return and shipping tickets from your Shopify inbox, flags anything that needs a human before it sends.", note: "Observed across 1,842 tickets", category: "Customer support", initials: "RR", color: "mint" },
  inventory: { title: "Low-Stock Watchkeeper", description: "Scans your catalog for velocity changes, writes a reorder brief, and keeps supplier follow-up in one calm daily digest.", note: "Observed across 14 storefronts", category: "Inventory & restocking", initials: "LW", color: "gold" },
  fulfillment: { title: "Delivery Exception Interpreter", description: "Turns carrier scans and missed promises into clear next steps, with a human-ready note for every order that needs attention.", note: "Observed across 9,404 shipments", category: "Order fulfillment", initials: "DE", color: "rust" },
  marketing: { title: "Campaign Recap Editor", description: "Turns weekly channel noise into a concise performance story, highlighting the creative, audience, and decision behind every signal.", note: "Observed across 62 weekly recaps", category: "Marketing & ads", initials: "CE", color: "blue" },
  feedback: { title: "Review & Feedback Signal Sorter", description: "Turns incoming feedback into a clear internal route, preserving the original words while keeping public responses and escalations with a human.", note: "Built for review-only feedback triage", category: "Reviews & feedback", initials: "FS", color: "feedback" },
};
const tabs = [["support", "Support"], ["inventory", "Inventory"], ["fulfillment", "Fulfillment"], ["marketing", "Marketing"], ["feedback", "Feedback"]] as const;
const tabIcons = { support: MessageSquareText, inventory: PackageSearch, fulfillment: Truck, marketing: Megaphone, feedback: ListFilter } as const;

const resolutionPaths = {
  return: { label: "Start a return", body: "I can help you begin the return process. Please keep the item and its original packaging available while we confirm the return details." },
  refund: { label: "Confirm a refund", body: "I can help clarify the refund path. I’ll first confirm the item status and the original payment method so the next step is accurate." },
  replacement: { label: "Request a replacement", body: "I can help check whether a replacement is available. I’ll confirm stock and the delivery details before promising an outcome." },
} as const;

type ResolutionPath = keyof typeof resolutionPaths;
type StockReview = { daysCover: number; reorderPoint: number; suggestedUnits: number; status: "Clear" | "Watch" | "Review now" };
const deliveryExceptions = {
  stalled: { label: "No movement since the latest scan", urgency: "Review today", action: "Request a carrier scan update before promising a new arrival date.", customer: "We are checking the shipment status and will share the next confirmed update." },
  missed: { label: "Delivery promise missed", urgency: "Escalate", action: "Check the latest carrier scan, then prepare a customer update with only confirmed timing.", customer: "The delivery estimate has passed. We are confirming the current shipment status before sharing a new date." },
  address: { label: "Address needs clarification", urgency: "Customer input", action: "Prepare an address-confirmation request and pause any replacement or resend decision.", customer: "The carrier needs one detail confirmed before delivery can continue." },
  delivered: { label: "Marked delivered, not received", urgency: "Review today", action: "Review the proof of delivery and carrier trace options before making a replacement or refund promise.", customer: "We are reviewing the delivery record and will confirm the available next step." },
} as const;
type DeliveryException = keyof typeof deliveryExceptions;
type CampaignReview = { roas: number; cpc: number; conversionRate: number; decision: string; decisionNote: string };
const feedbackPaths = {
  praise: { label: "Positive signal", priority: "Share with team", action: "Log the positive signal with the relevant product or workflow owner. Do not turn it into a public claim without consent.", response: "A person may choose to acknowledge the feedback through the appropriate channel." },
  request: { label: "Feature or product request", priority: "Product review", action: "Record the request alongside affected product context, then review it against existing research and planned work.", response: "A person may choose whether a response would be useful; do not promise a roadmap or delivery date." },
  issue: { label: "Product or service issue", priority: "Experience review", action: "Route the issue to the responsible team with the original detail intact. Check whether an order, support, or safety workflow should take over.", response: "A person should confirm the facts before any reply, remedy, or public response." },
  risk: { label: "Safety, legal, or trust concern", priority: "Escalate", action: "Keep the feedback private and flag it for the designated responsible reviewer before any further action.", response: "Do not publish, debate, or promise an outcome from this workspace." },
} as const;
type FeedbackPath = keyof typeof feedbackPaths;
type FeedbackReview = { excerpt: string; priority: string; action: string; response: string; label: string };
type ThemePreference = "system" | "light" | "dark";

export default function Agents() {

  const [activeTab, setActiveTab] = useState<(typeof tabs)[number][0]>("support");
  const [themePreference, setThemePreference] = useState<ThemePreference>(() => { const saved = window.localStorage.getItem("folklore-theme-preference"); return saved === "light" || saved === "dark" || saved === "system" ? saved : "system"; });
  const [systemTheme, setSystemTheme] = useState<"light" | "dark">(() => window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light");
  const [themeMenuOpen, setThemeMenuOpen] = useState(false);
  const [rating, setRating] = useState(0);
  const [liked, setLiked] = useState(false);
  const [menuOpen, setMenuOpen] = useState(false);
  const [scrolled, setScrolled] = useState(false);
  const [customerName, setCustomerName] = useState("Maya");
  const [orderNumber, setOrderNumber] = useState("#10482");
  const [resolutionPath, setResolutionPath] = useState<ResolutionPath>("return");
  const [ticket, setTicket] = useState("Hi — the jacket from my latest order does not fit. It is unworn and I would like to return it. Could you tell me what I need to do next?");
  const [policyNote, setPolicyNote] = useState("Returns are accepted within 30 days when items are unworn and in their original condition.");
  const [draftStatus, setDraftStatus] = useState("Draft-only mode · nothing will be sent");
  const [copied, setCopied] = useState(false);
  const [productName, setProductName] = useState("Aster Ribbed Tumbler");
  const [sku, setSku] = useState("AST-RIB-12");
  const [unitsOnHand, setUnitsOnHand] = useState("24");
  const [dailyDemand, setDailyDemand] = useState("6");
  const [supplierLeadDays, setSupplierLeadDays] = useState("7");
  const [targetCoverDays, setTargetCoverDays] = useState("21");
  const [stockReview, setStockReview] = useState<StockReview>({ daysCover: 4, reorderPoint: 42, suggestedUnits: 102, status: "Review now" });
  const [supplierQueued, setSupplierQueued] = useState(false);
  const [deliveryOrder, setDeliveryOrder] = useState("#10519");
  const [carrier, setCarrier] = useState("Northline Parcel");
  const [exceptionType, setExceptionType] = useState<DeliveryException>("missed");
  const [lastScan, setLastScan] = useState("Departed regional facility · 2 days ago");
  const [deliveryPromise, setDeliveryPromise] = useState("Expected yesterday");
  const [exceptionQueued, setExceptionQueued] = useState(false);
  const [campaignName, setCampaignName] = useState("Spring Room Edit");
  const [channel, setChannel] = useState("Paid social");
  const [audience, setAudience] = useState("Returning visitors · 30 days");
  const [creative, setCreative] = useState("Ceramic carousel / room edit");
  const [spend, setSpend] = useState("860");
  const [revenue, setRevenue] = useState("2980");
  const [clicks, setClicks] = useState("1240");
  const [orders, setOrders] = useState("38");
  const [campaignReview, setCampaignReview] = useState<CampaignReview>({ roas: 3.47, cpc: 0.69, conversionRate: 3.1, decision: "Consider cautious scale", decisionNote: "The return is strong enough to test a small budget increase, but review creative fatigue and attribution before changing spend." });
  const [campaignQueued, setCampaignQueued] = useState(false);
  const [feedbackSource, setFeedbackSource] = useState("Store review");
  const [feedbackProduct, setFeedbackProduct] = useState("");
  const [feedbackText, setFeedbackText] = useState("");
  const [feedbackPath, setFeedbackPath] = useState<FeedbackPath>("issue");
  const [feedbackQueued, setFeedbackQueued] = useState(false);
  const [feedbackReview, setFeedbackReview] = useState<FeedbackReview>({ excerpt: "No feedback has been added yet.", priority: "Experience review", action: "Add feedback and prepare a private review brief.", response: "Nothing will be published or sent from this workspace.", label: "Product or service issue" });
  const agent = useMemo(() => agents[activeTab], [activeTab]);
  const resolvedTheme = themePreference === "system" ? systemTheme : themePreference;
  useEffect(() => { const onScroll = () => setScrolled(window.scrollY > 32); window.addEventListener("scroll", onScroll, { passive: true }); return () => window.removeEventListener("scroll", onScroll); }, []);
  useEffect(() => { const mediaQuery = window.matchMedia("(prefers-color-scheme: dark)"); const syncSystemTheme = () => setSystemTheme(mediaQuery.matches ? "dark" : "light"); mediaQuery.addEventListener("change", syncSystemTheme); return () => mediaQuery.removeEventListener("change", syncSystemTheme); }, []);
  useEffect(() => { window.localStorage.setItem("folklore-theme-preference", themePreference); document.documentElement.style.colorScheme = resolvedTheme; }, [themePreference, resolvedTheme]);
  const closeMenu = () => setMenuOpen(false);
  const selectTab = (key: (typeof tabs)[number][0]) => { setActiveTab(key); setRating(0); };
  const prepareDraft = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const firstName = customerName.trim() || "there";
    const orderReference = orderNumber.trim() ? ` regarding order ${orderNumber.trim()}` : "";
    const request = ticket.trim().replace(/\s+/g, " ").slice(0, 240);
    const path = resolutionPaths[resolutionPath];
    setDraft(`Hi ${firstName},\n\nThanks for reaching out${orderReference}. I’ve read your note${request ? ` about “${request}”` : ""}.\n\n${path.body}${policyNote.trim() ? `\n\nFor reference, our current policy note is: ${policyNote.trim()}` : ""}\n\nBefore anything is finalized, please confirm that the item is unworn and in its original condition. Once that is confirmed, we can share the next step.\n\nBest,\nFolklore Support`);
    setDraftStatus("Draft prepared · review and approve before sending");
    setCopied(false);
  };
  const resetDraft = () => { setCustomerName("Maya"); setOrderNumber("#10482"); setResolutionPath("return"); setTicket("Hi — the jacket from my latest order does not fit. It is unworn and I would like to return it. Could you tell me what I need to do next?"); setPolicyNote("Returns are accepted within 30 days when items are unworn and in their original condition."); setDraftStatus("Draft-only mode · nothing will be sent"); setCopied(false); };
  const [draft, setDraft] = useState("Hi Maya,\n\nThanks for reaching out regarding order #10482. I can help with the next step for your return. Before anything is finalized, please confirm that the jacket is unworn and in its original condition.\n\nOnce that is confirmed, we can share the return instructions.\n\nBest,\nFolklore Support");
  const copyDraft = async () => { try { await navigator.clipboard.writeText(draft); setCopied(true); } catch { setCopied(false); } };
  const prepareStockReview = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const units = Math.max(0, Number(unitsOnHand) || 0);
    const daily = Math.max(0.1, Number(dailyDemand) || 0.1);
    const leadDays = Math.max(1, Number(supplierLeadDays) || 1);
    const targetDays = Math.max(leadDays, Number(targetCoverDays) || leadDays);
    const daysCover = Math.round((units / daily) * 10) / 10;
    const reorderPoint = Math.ceil(daily * leadDays);
    const suggestedUnits = Math.max(0, Math.ceil(daily * targetDays - units));
    const status = units <= reorderPoint ? "Review now" : daysCover <= targetDays ? "Watch" : "Clear";
    setStockReview({ daysCover, reorderPoint, suggestedUnits, status });
    setSupplierQueued(false);
  };
  const resetStockReview = () => { setProductName("Aster Ribbed Tumbler"); setSku("AST-RIB-12"); setUnitsOnHand("24"); setDailyDemand("6"); setSupplierLeadDays("7"); setTargetCoverDays("21"); setStockReview({ daysCover: 4, reorderPoint: 42, suggestedUnits: 102, status: "Review now" }); setSupplierQueued(false); };
  const resetDeliveryException = () => { setDeliveryOrder("#10519"); setCarrier("Northline Parcel"); setExceptionType("missed"); setLastScan("Departed regional facility · 2 days ago"); setDeliveryPromise("Expected yesterday"); setExceptionQueued(false); };
  const deliveryCase = deliveryExceptions[exceptionType];
  const prepareExceptionReview = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setExceptionQueued(false); };
  const prepareCampaignReview = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const spendValue = Math.max(0, Number(spend) || 0);
    const revenueValue = Math.max(0, Number(revenue) || 0);
    const clicksValue = Math.max(0, Number(clicks) || 0);
    const ordersValue = Math.max(0, Number(orders) || 0);
    const roas = spendValue > 0 ? Math.round((revenueValue / spendValue) * 100) / 100 : 0;
    const cpc = clicksValue > 0 ? Math.round((spendValue / clicksValue) * 100) / 100 : 0;
    const conversionRate = clicksValue > 0 ? Math.round((ordersValue / clicksValue) * 1000) / 10 : 0;
    const decision = roas >= 3 && conversionRate >= 2.5 ? "Consider cautious scale" : roas >= 1.5 ? "Hold and inspect" : "Refresh before more spend";
    const decisionNote = decision === "Consider cautious scale" ? "The return and conversion rate support a controlled test, but review attribution and creative frequency before any budget change." : decision === "Hold and inspect" ? "The campaign is producing a signal, but the next decision should follow a check on audience quality, creative fatigue, and marginal return." : "The current efficiency does not support increasing spend. Review the offer, creative, and audience before restarting or reallocating budget.";
    setCampaignReview({ roas, cpc, conversionRate, decision, decisionNote });
    setCampaignQueued(false);
  };
  const resetCampaignReview = () => { setCampaignName("Spring Room Edit"); setChannel("Paid social"); setAudience("Returning visitors · 30 days"); setCreative("Ceramic carousel / room edit"); setSpend("860"); setRevenue("2980"); setClicks("1240"); setOrders("38"); setCampaignReview({ roas: 3.47, cpc: 0.69, conversionRate: 3.1, decision: "Consider cautious scale", decisionNote: "The return is strong enough to test a small budget increase, but review creative fatigue and attribution before changing spend." }); setCampaignQueued(false); };
  const prepareFeedbackReview = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const path = feedbackPaths[feedbackPath];
    const excerpt = feedbackText.trim().replace(/\s+/g, " ").slice(0, 360) || "No feedback has been added yet.";
    setFeedbackReview({ excerpt, priority: path.priority, action: path.action, response: path.response, label: path.label });
    setFeedbackQueued(false);
  };
  const resetFeedbackReview = () => { setFeedbackSource("Store review"); setFeedbackProduct(""); setFeedbackText(""); setFeedbackPath("issue"); setFeedbackQueued(false); setFeedbackReview({ excerpt: "No feedback has been added yet.", priority: "Experience review", action: "Add feedback and prepare a private review brief.", response: "Nothing will be published or sent from this workspace.", label: "Product or service issue" }); };

  const selectThemePreference = (preference: ThemePreference) => { setThemePreference(preference); setThemeMenuOpen(false); };
  const ThemeIcon = themePreference === "system" ? Monitor : resolvedTheme === "dark" ? Moon : Sun;

  return <div className={`folklore-page theme-${resolvedTheme}`}>
    <header className={`site-header ${scrolled ? "is-scrolled" : ""}`}>
      <a className="wordmark" href="#top" onClick={closeMenu} aria-label="Folklore home"><span className="wordmark-mark"><img src="/manus-storage/folklore-mark_b6f5994d.png" alt="" /></span><span>Folk<span>lore</span></span></a>
      <div className="header-actions"><div className="theme-control"><button className="theme-toggle" type="button" onClick={() => setThemeMenuOpen((open) => !open)} aria-label={`Theme preference: ${themePreference}. Current appearance: ${resolvedTheme}.`} aria-haspopup="menu" aria-expanded={themeMenuOpen} title="Choose theme preference"><ThemeIcon size={15} /><span>{themePreference === "system" ? "System" : themePreference === "dark" ? "Dark" : "Light"}</span><ChevronDown size={13} className={themeMenuOpen ? "is-open" : ""} /></button><div className={`theme-picker ${themeMenuOpen ? "open" : ""}`} role="menu" aria-label="Theme preference"><button type="button" role="menuitemradio" aria-checked={themePreference === "system"} className={themePreference === "system" ? "active" : ""} onClick={() => selectThemePreference("system")}><Monitor size={15} /><span>System</span><small>Matches your OS</small></button><button type="button" role="menuitemradio" aria-checked={themePreference === "light"} className={themePreference === "light" ? "active" : ""} onClick={() => selectThemePreference("light")}><Sun size={15} /><span>Light</span></button><button type="button" role="menuitemradio" aria-checked={themePreference === "dark"} className={themePreference === "dark" ? "active" : ""} onClick={() => selectThemePreference("dark")}><Moon size={15} /><span>Dark</span></button></div></div><button className="mobile-menu-toggle" type="button" onClick={() => setMenuOpen((open) => !open)} aria-label={menuOpen ? "Close navigation" : "Open navigation"} aria-expanded={menuOpen}>{menuOpen ? <X size={22} /> : <Menu size={22} />}</button></div>
      <nav className={`main-nav ${menuOpen ? "open" : ""}`} aria-label="Main navigation">
        <a href="/" onClick={closeMenu}>Home</a><a href="#agent-library" onClick={closeMenu}>Agent records</a><a href="#drafter" onClick={closeMenu}>Try the drafter</a><a href="#watchkeeper" onClick={closeMenu}>Watch stock</a><a href="/#pricing" onClick={closeMenu}>Plans</a><a className="nav-cta" href="#drafter" onClick={closeMenu}>Open the workspace <ArrowUpRight size={14} /></a>
      </nav>
    </header>

    <main id="top">
      <section className="hero" aria-labelledby="hero-title">
        <div className="hero-image-wrap"><img className="hero-image" src="/manus-storage/folklore-hero_5b8b317d.webp" alt="Aerial view of a green forest canopy with white birds flying across it" /><div className="hero-image-wash" /><div className="hero-image-caption"><span>Field note 001</span><span>Canopy / in motion</span></div></div>
        <div className="hero-copy"><div className="eyebrow eyebrow-light"><span className="eyebrow-dot" /> A marketplace built on record, not rating</div><h1 id="hero-title">Every agent here has a <em>story.</em></h1><p className="hero-sub">Folklore is where AI agents for e-commerce ops earn their reputation — through real tasks, real outputs, and the people who have actually run them.</p><div className="hero-actions"><a className="button button-primary" href="#drafter">Try the drafter <ArrowRight size={16} /></a><a className="button button-ghost" href="#agents">Browse agents <ArrowUpRight size={16} /></a></div><div className="hero-proof"><div><strong>01</strong><span>Read the record</span></div><div><strong>02</strong><span>Run the task</span></div><div><strong>03</strong><span>Share what changed</span></div></div></div>
        <div className="hero-side-note"><span>Trusted by operators</span><strong>who prefer proof<br />to promises.</strong><ArrowDownRight size={20} /></div>
      </section>

      <div className="seal-divider" aria-hidden="true"><span className="rule" /><span className="seal">◆ Told, tested, trusted ◆</span><span className="rule" /></div>

      <section className="section-shell categories-section" id="agent-library" aria-labelledby="agents-title">
        <div className="section-intro"><div className="eyebrow"><span className="eyebrow-dot" /> Browse by field</div><h2 id="agents-title">A better way to find the right <em>help.</em></h2><p>Each field opens a record and a review-ready workspace. The landing page stays concise; the work itself lives here.</p><a className="text-link" href="#featured">Open an agent record <ArrowUpRight size={15} /></a></div>
        <div className="category-grid">{categories.map((category, index) => <a className={`category-card card-${index + 1}`} href="#featured" key={category.title} onClick={() => selectTab(index === 0 ? "support" : index === 1 ? "inventory" : index === 2 ? "fulfillment" : index === 3 ? "marketing" : "feedback")}><span className="card-index">{category.number}</span><span className="category-icon" aria-hidden="true">{category.icon}</span><h3>{category.title}</h3><p>{category.text}</p><span className="card-arrow"><ArrowUpRight size={16} /></span></a>)}</div>
      </section>

      <section className="archive-band" id="forum" aria-labelledby="forum-title"><div className="archive-pattern" /><div className="archive-inner"><div className="archive-heading"><div className="eyebrow eyebrow-gold"><span className="eyebrow-dot" /> The forum</div><h2 id="forum-title">The part the listing <em>can’t</em> tell you.</h2><p>Operators leave the context behind the result: the odd edge case, the workflow it replaced, the thing they would do differently next time.</p><a className="button button-light" href="#submit">Read the field notes <ArrowRight size={16} /></a></div><div className="thread-list"><div className="thread-card"><div><span className="thread-kicker">Customer support · 12 min read</span><h3>“It got the tone right because we gave it a boundary.”</h3></div><ArrowUpRight size={18} /></div><div className="thread-card"><div><span className="thread-kicker">Inventory · 8 min read</span><h3>What changed when the reorder brief became daily.</h3></div><ArrowUpRight size={18} /></div><div className="thread-card"><div><span className="thread-kicker">Fulfillment · 5 min read</span><h3>A missed delivery is a story before it is a ticket.</h3></div><ArrowUpRight size={18} /></div><div className="archive-quote"><Quote size={20} /><p>“The useful part wasn’t automation. It was finally seeing the pattern.”</p><span>— Marina, home goods operator</span></div></div></div></section>

      <section className="section-shell featured-section" id="featured" aria-labelledby="featured-title"><div className="featured-header"><div><div className="eyebrow"><span className="eyebrow-dot" /> Open record / 05</div><h2 id="featured-title">Featured agent</h2></div><p className="featured-header-note">A living sample from the Folklore archive.<br />Switch fields to see how the record changes.</p></div><div className="pill-tabs" role="tablist" aria-label="Featured agent categories">{tabs.map(([key, label]) => { const TabIcon = tabIcons[key]; return <button key={key} type="button" role="tab" aria-selected={activeTab === key} className={activeTab === key ? "active" : ""} onClick={() => selectTab(key)}><TabIcon size={14} aria-hidden="true" /><span>{label}</span></button>; })}</div><div className="agent-record"><div className={`agent-avatar ${agent.color}`}>{agent.initials}<span className="avatar-check"><Check size={11} /></span></div><div className="agent-main"><div className="record-meta"><span className="live-dot" /> Verified field note <span className="meta-separator">/</span> {agent.category}</div><h3>{agent.title}</h3><p>{agent.description}</p><details className="agent-details"><summary>Expand record details <ChevronDown size={16} /></summary><div><p><strong>How it is used:</strong> Start with the task, add the relevant context, and keep an operator responsible for any action that changes a customer, supplier, or order outcome.</p><p><strong>Example:</strong> A team uses this record to review the next step, not to authorize an automatic send, purchase, or customer promise.</p></div></details><div className="agent-footer"><span className="agent-observation"><Activity size={15} /> {agent.note}</span><div className="rating-wrap" aria-label={`Rate ${agent.title}`}><span className="rating-label">Your read</span><div className="stars">{[1, 2, 3, 4, 5].map((star) => <button className={star <= rating ? "star on" : "star"} type="button" aria-label={`${star} star${star > 1 ? "s" : ""}`} key={star} onClick={() => setRating(star)}><Star size={18} fill="currentColor" /></button>)}</div></div></div></div><div className="agent-side"><span className="record-number">FN—{String(tabs.findIndex(([key]) => key === activeTab) + 1).padStart(2, "0")}</span><button className={`like-button ${liked ? "liked" : ""}`} type="button" aria-pressed={liked} onClick={() => setLiked((value) => !value)}><Heart size={16} fill={liked ? "currentColor" : "none"} /><span>{liked ? 129 : 128}</span></button><span className="like-caption">Operators saved this record</span></div></div></section>

      <section className="drafter-section" id="drafter" aria-labelledby="drafter-title">
        <div className="drafter-heading"><div><div className="eyebrow"><span className="eyebrow-dot" /> Agent workspace / support</div><h2 id="drafter-title">Return &amp; refund <em>ticket drafter.</em></h2></div><p>A private drafting bench for your support team. Add the context, prepare a reply, and keep the final send with a human.</p></div>
        <div className="drafter-guardrail"><ShieldCheck size={18} /><span><strong>Human approval is required.</strong> This workspace prepares text only; it cannot access inboxes, place refunds, or send a customer message.</span></div>
        <form className="drafter-console" onSubmit={prepareDraft}>
          <div className="draft-inputs"><div className="form-heading"><MessageSquareText size={18} /><div><span>01 / Gather the record</span><h3>Ticket context</h3></div></div><div className="form-grid"><label>Customer name<input value={customerName} onChange={(event) => setCustomerName(event.target.value)} placeholder="Customer first name" /></label><label>Order reference<input value={orderNumber} onChange={(event) => setOrderNumber(event.target.value)} placeholder="#10482" /></label></div><label>Desired next step<select value={resolutionPath} onChange={(event) => setResolutionPath(event.target.value as ResolutionPath)}>{Object.entries(resolutionPaths).map(([key, option]) => <option key={key} value={key}>{option.label}</option>)}</select></label><label>Customer message<textarea value={ticket} onChange={(event) => setTicket(event.target.value)} rows={6} placeholder="Paste the support ticket here" /></label><label>Relevant policy note<textarea value={policyNote} onChange={(event) => setPolicyNote(event.target.value)} rows={3} placeholder="Add the policy detail that should guide the response" /></label><div className="drafter-actions"><button className="button button-primary" type="submit"><Sparkles size={16} /> Prepare a draft</button><button className="plain-action" type="button" onClick={resetDraft}><RotateCcw size={15} /> Reset example</button></div></div>
          <article className="draft-output" aria-live="polite"><div className="draft-output-head"><div className="form-heading"><FileText size={18} /><div><span>02 / Review before sending</span><h3>Prepared reply</h3></div></div><span className="draft-status"><span className="live-dot" /> {draftStatus}</span></div><div className="draft-paper"><p>{draft}</p></div><div className="draft-output-foot"><span><ClipboardCheck size={15} /> No automatic send</span><button className="copy-action" type="button" onClick={copyDraft}><Copy size={15} /> {copied ? "Copied to clipboard" : "Copy draft"}</button></div></article>
        </form>
        <details className="workspace-details"><summary>Expand examples and review boundaries <ChevronDown size={16} /></summary><div className="drafter-notes"><div><span>01</span><p>Use only the facts in the ticket and approved policy notes.</p></div><div><span>02</span><p>Flag exceptions, payment promises, or unclear order details for a person.</p></div><div><span>03</span><p>Approve, adapt, and send the final message from your own support system.</p></div></div></details>
      </section>

      <section className="watchkeeper-section" id="watchkeeper" aria-labelledby="watchkeeper-title">
        <div className="watchkeeper-heading"><div><div className="eyebrow eyebrow-gold"><span className="eyebrow-dot" /> Agent workspace / inventory</div><h2 id="watchkeeper-title">Low-stock <em>watchkeeper.</em></h2></div><p>Turn a small inventory snapshot into a calm review note. The final supplier conversation stays with your team.</p></div>
        <div className="watchkeeper-guardrail"><ShieldCheck size={18} /><span><strong>Review-only inventory planning.</strong> This workspace does not connect to stock systems, change inventory, or contact suppliers.</span></div>
        <form className="watchkeeper-console" onSubmit={prepareStockReview}>
          <div className="watch-inputs"><div className="form-heading"><Box size={18} /><div><span>01 / Set the snapshot</span><h3>Stock context</h3></div></div><div className="form-grid"><label>Product name<input value={productName} onChange={(event) => setProductName(event.target.value)} placeholder="Product name" /></label><label>SKU<input value={sku} onChange={(event) => setSku(event.target.value)} placeholder="SKU" /></label><label>Units on hand<input value={unitsOnHand} onChange={(event) => setUnitsOnHand(event.target.value)} inputMode="decimal" /></label><label>Average daily units sold<input value={dailyDemand} onChange={(event) => setDailyDemand(event.target.value)} inputMode="decimal" /></label><label>Supplier lead time / days<input value={supplierLeadDays} onChange={(event) => setSupplierLeadDays(event.target.value)} inputMode="numeric" /></label><label>Target cover / days<input value={targetCoverDays} onChange={(event) => setTargetCoverDays(event.target.value)} inputMode="numeric" /></label></div><div className="drafter-actions"><button className="button button-light" type="submit"><Sparkles size={16} /> Prepare review</button><button className="plain-action watch-reset" type="button" onClick={resetStockReview}><RotateCcw size={15} /> Reset example</button></div></div>
          <article className="stock-output" aria-live="polite"><div className="stock-output-head"><div className="form-heading"><ClipboardList size={18} /><div><span>02 / Human supplier review</span><h3>Reorder brief</h3></div></div><span className={`stock-status status-${stockReview.status.toLowerCase().replace(" ", "-")}`}><span className="live-dot" /> {stockReview.status}</span></div><div className="stock-product"><span>{sku || "SKU pending"}</span><h3>{productName || "Unnamed product"}</h3></div><div className="stock-metrics"><div><span>Current cover</span><strong>{stockReview.daysCover}<small> days</small></strong></div><div><span>Review threshold</span><strong>{stockReview.reorderPoint}<small> units</small></strong></div><div><span>Suggested discussion</span><strong>{stockReview.suggestedUnits}<small> units</small></strong></div></div><p className="stock-brief">At the current pace, this item has about <strong>{stockReview.daysCover} days</strong> of cover. The lead-time threshold is <strong>{stockReview.reorderPoint} units</strong>. Use the suggested quantity as a starting point for a supplier conversation, then confirm availability, cash flow, and demand changes.</p><div className="stock-output-foot"><span><ClipboardCheck size={15} /> No supplier has been contacted</span><button className="supplier-action" type="button" onClick={() => setSupplierQueued((value) => !value)}>{supplierQueued ? <Check size={15} /> : <ArrowRight size={15} />}{supplierQueued ? "Marked for review" : "Mark for supplier review"}</button></div></article>
        </form>
        <details className="workspace-details watch-details"><summary>Expand calculation and example context <ChevronDown size={16} /></summary><div className="watch-notes"><p><strong>Example:</strong> With 24 units on hand, six units sold daily, and a seven-day supplier lead time, the review threshold is 42 units. The workspace surfaces the gap; it does not place an order.</p><p><strong>Calculation:</strong> Review threshold equals average daily units sold × supplier lead time. Suggested discussion quantity uses target cover minus current units.</p></div></details>
      </section>

      <section className="exception-section" id="exceptions" aria-labelledby="exception-title">
        <div className="exception-heading"><div><div className="eyebrow"><span className="eyebrow-dot" /> Agent workspace / fulfillment</div><h2 id="exception-title">Delivery exception <em>interpreter.</em></h2></div><p>Bring a carrier update into the open, identify the next responsible action, and keep every customer promise under human review.</p></div>
        <div className="exception-guardrail"><ShieldCheck size={18} /><span><strong>Review-only delivery triage.</strong> This workspace cannot contact carriers, send customer messages, issue replacements, or alter an order.</span></div>
        <form className="exception-console" onSubmit={prepareExceptionReview}>
          <div className="exception-inputs"><div className="form-heading"><Truck size={18} /><div><span>01 / Read the trail</span><h3>Shipment context</h3></div></div><div className="form-grid"><label>Order reference<input value={deliveryOrder} onChange={(event) => setDeliveryOrder(event.target.value)} placeholder="#10519" /></label><label>Carrier<input value={carrier} onChange={(event) => setCarrier(event.target.value)} placeholder="Carrier name" /></label></div><label>Exception type<select value={exceptionType} onChange={(event) => setExceptionType(event.target.value as DeliveryException)}>{Object.entries(deliveryExceptions).map(([key, item]) => <option value={key} key={key}>{item.label}</option>)}</select></label><label>Latest carrier scan<textarea value={lastScan} onChange={(event) => setLastScan(event.target.value)} rows={3} placeholder="Paste the latest carrier status" /></label><label>Current delivery expectation<input value={deliveryPromise} onChange={(event) => setDeliveryPromise(event.target.value)} placeholder="For example: expected yesterday" /></label><div className="drafter-actions"><button className="button button-primary" type="submit"><Sparkles size={16} /> Prepare next step</button><button className="plain-action exception-reset" type="button" onClick={resetDeliveryException}><RotateCcw size={15} /> Reset example</button></div></div>
          <article className="exception-output" aria-live="polite"><div className="exception-output-head"><div className="form-heading"><PackageSearch size={18} /><div><span>02 / Human order review</span><h3>Exception brief</h3></div></div><span className={`exception-status status-${deliveryCase.urgency.toLowerCase().replace(" ", "-")}`}><AlertTriangle size={14} /> {deliveryCase.urgency}</span></div><div className="exception-order"><span>{deliveryOrder || "Order pending"} <i>·</i> {carrier || "Carrier pending"}</span><h3>{deliveryCase.label}</h3></div><div className="exception-trail"><div><MapPin size={16} /><div><span>Latest carrier scan</span><p>{lastScan || "No scan details supplied"}</p></div></div><div><Activity size={16} /><div><span>Delivery expectation</span><p>{deliveryPromise || "No expectation supplied"}</p></div></div></div><div className="exception-next"><span>Suggested next action</span><p>{deliveryCase.action}</p></div><div className="customer-language"><MessageSquareText size={16} /><div><span>Optional customer language for review</span><p>“{deliveryCase.customer}”</p></div></div><div className="exception-output-foot"><span><ClipboardCheck size={15} /> No customer or carrier contact</span><button className="exception-action" type="button" onClick={() => setExceptionQueued((value) => !value)}>{exceptionQueued ? <Check size={15} /> : <ArrowRight size={15} />}{exceptionQueued ? "Marked for order review" : "Mark for order review"}</button></div></article>
        </form>
        <details className="workspace-details exception-details"><summary>Expand examples and review boundaries <ChevronDown size={16} /></summary><div className="exception-notes"><p><strong>Example:</strong> A missed delivery estimate with no new scan should trigger carrier status review before a customer receives a revised date.</p><p><strong>Boundary:</strong> Do not promise a refund, replacement, reshipment, or delivery date from this workspace. Make that decision in the order system after reviewing the evidence.</p></div></details>
      </section>

      <section className="recap-section" id="recap" aria-labelledby="recap-title">
        <div className="recap-heading"><div><div className="eyebrow eyebrow-gold"><span className="eyebrow-dot" /> Agent workspace / marketing</div><h2 id="recap-title">Campaign recap <em>editor.</em></h2></div><p>Turn a compact performance snapshot into a reviewable story about the creative, audience, and next decision.</p></div>
        <div className="recap-guardrail"><ShieldCheck size={18} /><span><strong>Review-only campaign planning.</strong> This workspace does not connect to ad platforms, edit budgets, publish creative, or change campaign targeting.</span></div>
        <form className="recap-console" onSubmit={prepareCampaignReview}>
          <div className="recap-inputs"><div className="form-heading"><Megaphone size={18} /><div><span>01 / Set the evidence</span><h3>Campaign context</h3></div></div><div className="form-grid"><label>Campaign name<input value={campaignName} onChange={(event) => setCampaignName(event.target.value)} placeholder="Campaign name" /></label><label>Channel<select value={channel} onChange={(event) => setChannel(event.target.value)}><option>Paid social</option><option>Search</option><option>Email</option><option>Affiliate</option></select></label></div><label>Audience<input value={audience} onChange={(event) => setAudience(event.target.value)} placeholder="Audience segment" /></label><label>Creative or offer<input value={creative} onChange={(event) => setCreative(event.target.value)} placeholder="Creative or offer" /></label><div className="form-grid metric-input-grid"><label>Spend<input value={spend} onChange={(event) => setSpend(event.target.value)} inputMode="decimal" placeholder="0" /></label><label>Attributed revenue<input value={revenue} onChange={(event) => setRevenue(event.target.value)} inputMode="decimal" placeholder="0" /></label><label>Clicks<input value={clicks} onChange={(event) => setClicks(event.target.value)} inputMode="numeric" placeholder="0" /></label><label>Orders<input value={orders} onChange={(event) => setOrders(event.target.value)} inputMode="numeric" placeholder="0" /></label></div><div className="drafter-actions"><button className="button button-light" type="submit"><Sparkles size={16} /> Prepare recap</button><button className="plain-action recap-reset" type="button" onClick={resetCampaignReview}><RotateCcw size={15} /> Reset example</button></div></div>
          <article className="recap-output" aria-live="polite"><div className="recap-output-head"><div className="form-heading"><BarChart3 size={18} /><div><span>02 / Human marketing review</span><h3>Performance story</h3></div></div><span className={`recap-status ${campaignReview.decision === "Refresh before more spend" ? "status-refresh" : campaignReview.decision === "Hold and inspect" ? "status-hold" : "status-scale"}`}><Target size={14} /> {campaignReview.decision}</span></div><div className="recap-campaign"><span>{channel} <i>·</i> {audience || "Audience pending"}</span><h3>{campaignName || "Untitled campaign"}</h3><p>{creative || "Creative pending"}</p></div><div className="recap-metrics"><div><span>ROAS</span><strong>{campaignReview.roas.toFixed(2)}<small>x</small></strong></div><div><span>Cost per click</span><strong>${campaignReview.cpc.toFixed(2)}</strong></div><div><span>Click-to-order</span><strong>{campaignReview.conversionRate.toFixed(1)}<small>%</small></strong></div></div><div className="recap-story"><span>Prepared recap</span><p><strong>{campaignName || "This campaign"}</strong> spent <strong>${Number(spend || 0).toLocaleString()}</strong> to attribute <strong>${Number(revenue || 0).toLocaleString()}</strong> in revenue, with {Number(clicks || 0).toLocaleString()} clicks and {Number(orders || 0).toLocaleString()} orders. The current signal comes from <strong>{creative || "the selected creative"}</strong> for <strong>{audience || "the selected audience"}</strong>.</p></div><div className="recap-decision"><CircleDollarSign size={16} /><div><span>Decision to review</span><p>{campaignReview.decisionNote}</p></div></div><div className="recap-output-foot"><span><ClipboardCheck size={15} /> No budget or creative change</span><button className="recap-action" type="button" onClick={() => setCampaignQueued((value) => !value)}>{campaignQueued ? <Check size={15} /> : <ArrowRight size={15} />}{campaignQueued ? "Marked for marketing review" : "Mark for marketing review"}</button></div></article>
        </form>
        <details className="workspace-details recap-details"><summary>Expand examples and review boundaries <ChevronDown size={16} /></summary><div className="recap-notes"><p><strong>Example:</strong> A high return may justify a controlled test, but only after checking attribution, creative frequency, and the marginal return from the next dollar spent.</p><p><strong>Boundary:</strong> This workspace assembles a recap from the inputs provided. It cannot validate platform reporting, adjust campaign settings, or publish a new audience or creative asset.</p></div></details>
      </section>

      <section className="feedback-section" id="feedback" aria-labelledby="feedback-title">
        <div className="feedback-heading"><div><div className="eyebrow"><span className="eyebrow-dot" /> Agent workspace / reviews &amp; feedback</div><h2 id="feedback-title">Feedback signal <em>sorter.</em></h2></div><p>Keep the original words close, add only the necessary context, and route the next internal review without publishing a response.</p></div>
        <div className="feedback-guardrail"><ShieldCheck size={18} /><span><strong>Private review only.</strong> This workspace does not post replies, publish feedback, change ratings, or make promises to a customer or reviewer.</span></div>
        <form className="feedback-console" onSubmit={prepareFeedbackReview}>
          <div className="feedback-inputs"><div className="form-heading"><ListFilter size={18} /><div><span>01 / Preserve the signal</span><h3>Feedback context</h3></div></div><div className="form-grid"><label>Source<select value={feedbackSource} onChange={(event) => setFeedbackSource(event.target.value)}><option>Store review</option><option>Support conversation</option><option>Social mention</option><option>Survey response</option></select></label><label>Review path<select value={feedbackPath} onChange={(event) => setFeedbackPath(event.target.value as FeedbackPath)}>{Object.entries(feedbackPaths).map(([key, path]) => <option key={key} value={key}>{path.label}</option>)}</select></label></div><label>Product or workflow context <span className="optional-label">optional</span><input value={feedbackProduct} onChange={(event) => setFeedbackProduct(event.target.value)} placeholder="For example: product name, support step, delivery moment" /></label><label>Feedback to review<textarea value={feedbackText} onChange={(event) => setFeedbackText(event.target.value)} rows={7} placeholder="Paste feedback here. It stays in this private review workspace." /></label><div className="drafter-actions"><button className="button button-primary" type="submit"><Sparkles size={16} /> Prepare review brief</button><button className="plain-action feedback-reset" type="button" onClick={resetFeedbackReview}><RotateCcw size={15} /> Reset</button></div></div>
          <article className="feedback-output" aria-live="polite"><div className="feedback-output-head"><div className="form-heading"><Flag size={18} /><div><span>02 / Human feedback review</span><h3>Private routing brief</h3></div></div><span className={`feedback-status ${feedbackReview.priority === "Escalate" ? "status-escalate" : feedbackReview.priority === "Share with team" ? "status-share" : "status-review"}`}>{feedbackReview.priority === "Escalate" ? <ShieldAlert size={14} /> : feedbackReview.priority === "Share with team" ? <ThumbsUp size={14} /> : <Flag size={14} />}{feedbackReview.priority}</span></div><div className="feedback-source"><span>{feedbackSource} <i>·</i> {feedbackProduct || "General feedback"}</span><h3>{feedbackReview.label}</h3></div><div className="feedback-excerpt"><span>Original feedback</span><p>{feedbackReview.excerpt}</p></div><div className="feedback-next"><span>Suggested internal route</span><p>{feedbackReview.action}</p></div><div className="feedback-response"><MessageSquareText size={16} /><div><span>Response boundary</span><p>{feedbackReview.response}</p></div></div><div className="feedback-output-foot"><span><ClipboardCheck size={15} /> No public response or rating change</span><button className="feedback-action" type="button" onClick={() => setFeedbackQueued((value) => !value)}>{feedbackQueued ? <Check size={15} /> : <ArrowRight size={15} />}{feedbackQueued ? "Marked for team review" : "Mark for team review"}</button></div></article>
        </form>
        <details className="workspace-details feedback-details"><summary>Expand examples and review boundaries <ChevronDown size={16} /></summary><div className="feedback-notes"><p><strong>Use the original words:</strong> Keep the actual feedback available to the responsible reviewer. Do not invent a rating, a quote, or an experience that was not provided.</p><p><strong>Boundary:</strong> Categorization is an internal prompt for review, not a final finding. A person decides whether to respond, escalate, improve a workflow, or record a product insight.</p></div></details>
      </section>

      <section className="process-section" id="verify" aria-labelledby="process-title"><div className="process-image"><img src="/manus-storage/folklore-botanical_ec118ecd.png" alt="Hand-inked botanical field guide illustration with birds and reeds" /><span className="image-stamp">No. 07<br />Field guide</span></div><div className="process-content"><div className="eyebrow eyebrow-light"><span className="eyebrow-dot" /> How it works</div><h2 id="process-title">Trust is a <em>trail,</em> not a badge.</h2><div className="steps"><div className="step"><span className="step-number">01</span><div><h3>Browse the record</h3><p>Start with the real task and the proof attached to it — not a promise about the future.</p></div></div><div className="step"><span className="step-number">02</span><div><h3>Run it in your world</h3><p>Try the workflow where it matters. Keep your edge cases close and your expectations legible.</p></div></div><div className="step"><span className="step-number">03</span><div><h3>Leave the next clue</h3><p>Share what changed so the next operator can make a better decision, faster.</p></div></div></div></div></section>

      <section className="closing-section" id="submit" aria-labelledby="closing-title"><div className="closing-mark"><BookOpen size={23} /><span>Archive note / 2026</span></div><div><div className="eyebrow"><span className="eyebrow-dot" /> For operators, by operators</div><h2 id="closing-title">Bring the work<br />worth <em>remembering.</em></h2></div><div className="closing-action"><p>Have an agent that earned its place in your stack? Give it a proper record.</p><a className="button button-primary" href="#top">Submit an agent <ArrowUpRight size={16} /></a></div></section>
    </main>

    <footer className="site-footer"><a className="wordmark footer-wordmark" href="#top"><span className="wordmark-mark"><img src="/manus-storage/folklore-mark_b6f5994d.png" alt="" /></span><span>Folk<span>lore</span></span></a><span>AI agents for the work behind the storefront.</span><span>© 2026 Folklore archive</span></footer>
  </div>;
}
